# Generated by Django 3.1 on 2020-08-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_text', '0002_book_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='release_time',
            field=models.DateField(default="2007-01-02", verbose_name='发布时间'),
            preserve_default=False,
        ),
    ]
