# Generated by Django 3.1 on 2020-08-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_text', '0003_book_release_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isdncode',
            field=models.CharField(default=1, max_length=20, verbose_name='国际编码'),
            preserve_default=False,
        ),
    ]
